puts "The students of my cohort at Makers Academy"
puts "Anath"
puts "Kennedy"
puts "Erica"
puts "Chris"
puts "Jean Baptiste"
puts "Tom"
puts "Tom"
puts "Simon"
puts "Anna"
puts "Laura"
puts "Jianne"
puts "Asta"
puts "Giorgi"
puts "james"
puts "James"
puts "Niki"
puts "Nisar"
puts "Giacomo"
puts "Michael"
puts "Peter"
puts "Bruce"
